In [42]:
import networkx as nx
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta, time
from DynamicTimeModel import DynTM
from Helper import *
from queryAlgorithm import earliestArrival_path, pareto_paths

### Import data

In [43]:
timetable = pd.read_csv('../dataPreprocessing/data/preprocessed_timetable.csv')
#timetable = timetable.sort_values(['nextStop_arrival_time'])
timetable.head()

,TripNb,line_id,vehicle_type,currentStop,nextStop,departure_time,nextStop_arrival_time,nextStop_deaprture_time
0,1,10,1,72,73,03:36:01,03:53:27,03:53:42
1,1,10,1,73,74,03:53:42,03:55:36,03:55:52
2,1,10,1,74,75,03:55:52,03:57:00,03:57:17
3,1,10,1,75,76,03:57:17,03:58:42,03:58:58
4,1,10,1,76,77,03:58:58,03:59:52,04:00:06

In [44]:
#convert str to time object
timetable.departure_time  = timetable.departure_time.apply(str_time_to_int)
timetable.nextStop_arrival_time = timetable.nextStop_arrival_time.apply(str_time_to_int)
timetable.nextStop_deaprture_time = timetable.nextStop_deaprture_time.apply(str_time_to_int)

In [45]:
Dmatrix = pd.read_csv('../dataPreprocessing/data/Dmatrix.csv')
Dmatrix = Dmatrix.set_index('station_id')

In [46]:
stations_paths = pd.read_csv('../dataPreprocessing/data/stations_paths.csv')
stations_coord = pd.read_csv('../dataPreprocessing/data/station_coord.csv')
paths = pd.read_csv('../dataPreprocessing/data/paths.csv')

In [47]:
stations = pd.concat([timetable.currentStop,timetable.nextStop]).reset_index(drop=True).unique()
stations_paths = stations_paths[stations_paths.station_id.isin(stations)]
stations_paths = stations_paths[['station_id', 'english_name', 'french_name', 'arabic_name','latitude','longitude']].drop_duplicates()

In [48]:
stations_coord = stations_coord[stations_coord.station_id.isin(stations)]

## Build DTM Graph Structure

In [49]:
#timetable data structre
timetable = (stations ,timetable.drop('TripNb', axis=1).values)

In [50]:
timetable[0].shape

(290,)

In [51]:
timetable[1].shape

(27967, 7)

In [52]:
#intiate graph
max_walk_between_stations = 300 #300meters
walk_speed  = 1.4  #1.4 meter per second
DTM = DynTM(max_walk_between_stations, stations_coord, walk_speed)

In [53]:
from time import time
#generate graph and add unrestricted path
start = time()
DTM.generateTimetableDynamicModel(timetable)
DTM.add_unresticted_paths(Dmatrix)
stop = time()
print(stop-start)

0.5046861171722412

In [54]:
DTM.dtm.number_of_nodes()

30205

In [55]:
DTM.dtm.number_of_edges()

84441

## DTM-QH algorithm to solve EA Problem

In [63]:
from time import time as timo

curr_time = datetime.now().time().replace(microsecond=0)
curr_time = str(curr_time.hour)+':'+str(curr_time.minute)+':'+str(curr_time.second)
curr_time = str_time_to_int(curr_time)
curr_time = str_time_to_int('17:10:00')

#source = ('source_node', 36.87007096206944, 10.34382253848957)   #sidi bou said
source = ('source_node', 36.87970216988326, 10.327309234021802)   #marsa ville
#target = ('target_node', 36.8226374125104, 10.30882462463282) #la goulette
#source = ('source_node', 36.83906834458209, 10.316478568193) #le kram
#target = ('target_node',36.8066962256805, 10.18126936246436) #siege IT transtu 
#target = ('target_node', 36.806678, 10.181269)   #Tunis marine
#target = ('target_node', 36.829968, 10.150268)  #manar1
#target = ('target_node', 36.724688, 10.205779)  #el mourouj 3
#target = ('target_node',36.85340441371543, 10.196437250933252)  #ariana
target = ('target_node', 36.81792285359155, 10.080213439106986)  #manouba
#target = ('target_node', 36.75537489487085, 10.22252052118309 ) #Ben Arouss
#target = ('target_node', 36.83848676642428, 10.183395901376352) #Manzeh 1 cité sportive
#target = ('target_node', 36.80936808780992, 10.133522078274913) #Musée bardo
#target = ('target_node', 36.796247434333004, 10.132042159557537) #ezzouhour
#target = ('target_node', 36.79086785239071, 10.092124602977709) #cité el mechtel
#target = ('target_node', 36.841494756981, 10.132237773927486) #Omrane sup
#target = ('target_node', 36.79037011799913, 10.107341203160626) #municipalité hrairia (ezzahrouni)
#target = ('target_node', 36.788855425031464, 10.177730508869596) #beb alioua
#target = ('target_node', 36.839583107126735, 10.117761184660045) #el intilaka

In [64]:
#add source node
coords =  source[1:]
DTM.add_sourceNode(coords, 2000)

In [65]:
#add target node
coords =  target[1:]
DTM.add_targetNode(coords, 2000)

In [66]:
start = timo()
path, transitions, walk = pareto_paths(DTM.dtm, source, target, curr_time, walk_panalisation=True, transfer_time=150)
stop = timo()
print(stop - start)

0.33611106872558594

In [67]:
walk

[1876, 1845]

In [68]:
transitions

[3, 2]

In [69]:
path

[['switch_source',
  ('switch', 89.0),
  ('node', 11, 89, 63031),
  ('node', 11, 88, 63180),
  ('node', 11, 87, 63301),
  ('node', 11, 86, 63458),
  ('node', 11, 85, 63594),
  ('node', 11, 84, 63720),
  ('node', 11, 83, 63856),
  ('node', 11, 82, 63954),
  ('node', 11, 81, 64051),
  ('node', 11, 80, 64164),
  ('node', 11, 79, 64279),
  ('node', 11, 78, 64395),
  ('node', 11, 77, 64478),
  ('node', 11, 76, 64577),
  ('node', 11, 75, 64708),
  ('node', 11, 74, 64827),
  ('node', 11, 73, 64986),
  ('switch', 72),
  ('switch', 69),
  ('node', 16, 69, 66528),
  ('node', 16, 70, 66701),
  ('switch', 14),
  ('node', 12, 14, 67210),
  ('node', 12, 13, 67772),
  ('node', 12, 12, 67959),
  ('node', 12, 11, 68083),
  ('node', 12, 10, 68231),
  ('node', 12, 90, 68472),
  ('node', 12, 91, 68602),
  ('node', 12, 92, 68786),
  ('node', 12, 93, 68924),
  ('node', 12, 94, 69028),
  ('node', 12, 95, 69154),
  ('node', 12, 96, 69282),
  ('node', 12, 97, 69533),
  ('node', 12, 98, 69680),
  ('node', 12, 99, 69809),
  ('switch', 100),
  'switch_target'],
 ['switch_source',
  ('switch', 89.0),
  ('node', 11, 89, 63031),
  ('node', 11, 88, 63180),
  ('node', 11, 87, 63301),
  ('node', 11, 86, 63458),
  ('node', 11, 85, 63594),
  ('node', 11, 84, 63720),
  ('node', 11, 83, 63856),
  ('node', 11, 82, 63954),
  ('node', 11, 81, 64051),
  ('node', 11, 80, 64164),
  ('node', 11, 79, 64279),
  ('node', 11, 78, 64395),
  ('node', 11, 77, 64478),
  ('node', 11, 76, 64577),
  ('node', 11, 75, 64708),
  ('node', 11, 74, 64827),
  ('node', 11, 73, 64986),
  ('switch', 72),
  ('switch', 15),
  ('node', 4, 15, 67423),
  ('node', 4, 16, 68351),
  ('node', 4, 17, 68535),
  ('node', 4, 18, 68771),
  ('node', 4, 19, 68877),
  ('node', 4, 20, 68975),
  ('node', 4, 21, 69043),
  ('node', 4, 22, 69141),
  ('node', 4, 23, 69291),
  ('node', 4, 24, 69427),
  ('node', 4, 25, 69504),
  ('node', 4, 26, 69578),
  ('node', 4, 27, 69716),
  ('node', 4, 28, 69868),
  ('node', 4, 29, 69914),
  ('node', 4, 30, 70019),
  ('node', 4, 31, 70054),
  ('node', 4, 32, 70186),
  ('node', 4, 33, 70265),
  ('switch', 34),
  'switch_target']]

In [ ]:
'''
print('---------------------Pareto--Set--Of--Optimal--Paths--Solution------------------------', end='\n\n')
for i, solution in enumerate(path) : 
    print('*Path N°',i+1, ' : ', end='\n\n')
    print(path_interpretor(solution, stations_paths, paths, language='french'))
    print('-------------------------------------------------------------------------------------', end='\n\n')
'''

In [70]:
start = timo()
path, dist, transistions, cc = earliestArrival_path(DTM.dtm, source, target, curr_time, walk_panalisation=True, transfer_time=150)
stop = timo()
print(stop - start)

0.15163207054138184

In [72]:
DTM.dtm[('switch', 89.0)]

AtlasView({('node', 11, 89, 15331): {'weight': 100000}, ('node', 11, 89, 18031): {'weight': 100000}, ('node', 11, 89, 20731): {'weight': 100000}, ('node', 11, 89, 22171): {'weight': 100000}, ('node', 11, 89, 23251): {'weight': 100000}, ('node', 11, 89, 24331): {'weight': 100000}, ('node', 11, 89, 25231): {'weight': 100000}, ('node', 11, 89, 26131): {'weight': 100000}, ('node', 11, 89, 27031): {'weight': 100000}, ('node', 11, 89, 27931): {'weight': 100000}, ('node', 11, 89, 28831): {'weight': 100000}, ('node', 11, 89, 29731): {'weight': 100000}, ('node', 11, 89, 30631): {'weight': 100000}, ('node', 11, 89, 31531): {'weight': 100000}, ('node', 11, 89, 32431): {'weight': 100000}, ('node', 11, 89, 33331): {'weight': 100000}, ('node', 11, 89, 34231): {'weight': 100000}, ('node', 11, 89, 35131): {'weight': 100000}, ('node', 11, 89, 36031): {'weight': 100000}, ('node', 11, 89, 36931): {'weight': 100000}, ('node', 11, 89, 37831): {'weight': 100000}, ('node', 11, 89, 38731): {'weight': 100000}, ('node', 11, 89, 39631): {'weight': 100000}, ('node', 11, 89, 40531): {'weight': 100000}, ('node', 11, 89, 41431): {'weight': 100000}, ('node', 11, 89, 42331): {'weight': 100000}, ('node', 11, 89, 43231): {'weight': 100000}, ('node', 11, 89, 44131): {'weight': 100000}, ('node', 11, 89, 45031): {'weight': 100000}, ('node', 11, 89, 45931): {'weight': 100000}, ('node', 11, 89, 46831): {'weight': 100000}, ('node', 11, 89, 47731): {'weight': 100000}, ('node', 11, 89, 48631): {'weight': 100000}, ('node', 11, 89, 49531): {'weight': 100000}, ('node', 11, 89, 50431): {'weight': 100000}, ('node', 11, 89, 51331): {'weight': 100000}, ('node', 11, 89, 52231): {'weight': 100000}, ('node', 11, 89, 53131): {'weight': 100000}, ('node', 11, 89, 54031): {'weight': 100000}, ('node', 11, 89, 54931): {'weight': 100000}, ('node', 11, 89, 55831): {'weight': 100000}, ('node', 11, 89, 56731): {'weight': 100000}, ('node', 11, 89, 57631): {'weight': 100000}, ('node', 11, 89, 58531): {'weight': 100000}, ('node', 11, 89, 59431): {'weight': 100000}, ('node', 11, 89, 60331): {'weight': 100000}, ('node', 11, 89, 61231): {'weight': 100000}, ('node', 11, 89, 62131): {'weight': 100000}, ('node', 11, 89, 63031): {'weight': 100000}, ('node', 11, 89, 63931): {'weight': 100000}, ('node', 11, 89, 64831): {'weight': 100000}, ('node', 11, 89, 65731): {'weight': 100000}, ('node', 11, 89, 66631): {'weight': 100000}, ('node', 11, 89, 67531): {'weight': 100000}, ('node', 11, 89, 68431): {'weight': 100000}, ('node', 11, 89, 69331): {'weight': 100000}, ('node', 11, 89, 70231): {'weight': 100000}, ('node', 11, 89, 71131): {'weight': 100000}, ('node', 11, 89, 72631): {'weight': 100000}, ('node', 11, 89, 74731): {'weight': 100000}, ('node', 11, 89, 77431): {'weight': 100000}, ('node', 11, 89, 80431): {'weight': 100000}, ('node', 11, 89, 82231): {'weight': 100000}, ('node', 11, 89, 85531): {'weight': 100000}, ('node', 11, 89, 931): {'weight': 100000}})

In [73]:
path

['switch_source',
 ('switch', 89.0),
 ('node', 11, 89, 63031),
 ('node', 11, 88, 63180),
 ('node', 11, 87, 63301),
 ('node', 11, 86, 63458),
 ('node', 11, 85, 63594),
 ('node', 11, 84, 63720),
 ('node', 11, 83, 63856),
 ('node', 11, 82, 63954),
 ('node', 11, 81, 64051),
 ('node', 11, 80, 64164),
 ('node', 11, 79, 64279),
 ('node', 11, 78, 64395),
 ('node', 11, 77, 64478),
 ('node', 11, 76, 64577),
 ('node', 11, 75, 64708),
 ('node', 11, 74, 64827),
 ('node', 11, 73, 64986),
 ('switch', 72),
 ('switch', 69),
 ('node', 16, 69, 66528),
 ('node', 16, 70, 66701),
 ('switch', 14),
 ('node', 12, 14, 67210),
 ('node', 12, 13, 67772),
 ('node', 12, 12, 67959),
 ('node', 12, 11, 68083),
 ('node', 12, 10, 68231),
 ('node', 12, 90, 68472),
 ('node', 12, 91, 68602),
 ('node', 12, 92, 68786),
 ('node', 12, 93, 68924),
 ('node', 12, 94, 69028),
 ('node', 12, 95, 69154),
 ('node', 12, 96, 69282),
 ('node', 12, 97, 69533),
 ('node', 12, 98, 69680),
 ('node', 12, 99, 69809),
 ('switch', 100),
 'switch_target']

In [ ]:
'''
print('---------------------Earliest--Arrival--Time--Path------------------------', end='\n\n')
print(path_interpretor(path, stations_paths, paths, language='french'))
'''

In [30]:
#remove source and target nodes from graph
DTM.remove_switch('switch_source')
DTM.remove_switch('switch_target')

### Path verfication

In [17]:
haversine_affinity(target[1:], [36.794313, 10.131666])

5189.559159100974

In [18]:
haversine_affinity(target[1:], [36.797900, 10.186210])

7664.126277551549

In [19]:
timetable[(timetable.line_id == 23) & (timetable.TripNb == 15)]

,TripNb,line_label,line_id,tag,order,prev_station,next_station,prev_latitude,prev_longitude,next_latitude,next_longitude,horaires_depart,horaires_arrivee,datetime_diff,vehicle_type,distance_diff
21800,15,32B,23,0,1,161,190,36.803734,10.178092,36.813544,10.172358,43200,43943,744.0,3,1206.0
23054,15,32B,23,0,2,190,191,36.813544,10.172358,36.809633,10.161708,43943,44088,144.0,3,1044.0
23165,15,32B,23,0,3,191,152,36.809633,10.161708,36.802780,10.163544,44088,44176,88.0,3,780.0
21323,15,32B,23,0,4,152,23,36.802780,10.163544,36.798979,10.161769,44176,44421,245.0,3,452.0
5402,15,32B,23,0,5,23,192,36.798979,10.161769,36.798186,10.153730,44421,44579,158.0,3,722.0
23300,15,32B,23,0,6,192,193,36.798186,10.153730,36.797979,10.150696,44579,44637,58.0,3,271.0
23438,15,32B,23,0,7,193,194,36.797979,10.150696,36.797204,10.146185,44637,44701,64.0,3,411.0
23570,15,32B,23,0,8,194,195,36.797204,10.146185,36.796703,10.143723,44701,44725,24.0,3,226.0
23752,15,32B,23,0,9,195,196,36.796703,10.143723,36.796037,10.138632,44725,44787,62.0,3,460.0
23934,15,32B,23,0,10,196,197,36.796037,10.138632,36.794313,10.131666,44787,44863,76.0,3,650.0
24116,15,32B,23,0,11,197,205,36.794313,10.131666,36.787522,10.124212,44863,45014,151.0,3,1007.0
24955,15,32B,23,0,12,205,206,36.787522,10.124212,36.781929,10.110381,45014,45279,265.0,3,1381.0
24983,15,32B,23,0,13,206,207,36.781929,10.110381,36.779725,10.102223,45279,45377,98.0,3,768.0
25011,15,32B,23,0,14,207,208,36.779725,10.102223,36.778413,10.096338,45377,45422,45.0,3,545.0
25039,15,32B,23,0,15,208,209,36.778413,10.096338,36.777018,10.091167,45422,45476,54.0,3,487.0
25067,15,32B,23,0,16,209,210,36.777018,10.091167,36.770346,10.080219,45476,45600,124.0,3,1227.0

In [20]:
timetable[(timetable.line_id == 4) & (timetable.TripNb == 10)]

,TripNb,line_label,line_id,tag,order,prev_station,next_station,prev_latitude,prev_longitude,next_latitude,next_longitude,horaires_depart,horaires_arrivee,datetime_diff,vehicle_type,distance_diff
5020,10,104,4,0,1,15,16,36.800174,10.190487,36.799103,10.186369,42600,43433,833.0,3,386.0
5068,10,104,4,0,2,16,17,36.799103,10.186369,36.792631,10.185839,43433,43605,172.0,3,722.0
5113,10,104,4,0,3,17,18,36.792631,10.185839,36.785595,10.179933,43605,43804,199.0,3,944.0
5154,10,104,4,0,4,18,19,36.785595,10.179933,36.784376,10.175823,43804,43888,84.0,3,391.0
5182,10,104,4,0,5,19,20,36.784376,10.175823,36.785284,10.171172,43888,43969,81.0,3,427.0
5214,10,104,4,0,6,20,21,36.785284,10.171172,36.787994,10.167514,43969,44011,42.0,3,444.0
5234,10,104,4,0,7,21,22,36.787994,10.167514,36.793260,10.163145,44011,44094,83.0,3,704.0
5254,10,104,4,0,8,22,23,36.793260,10.163145,36.798979,10.161769,44094,44217,123.0,3,648.0
5400,10,104,4,0,9,23,24,36.798979,10.161769,36.799937,10.154693,44217,44342,125.0,3,640.0
5569,10,104,4,0,10,24,25,36.799937,10.154693,36.801774,10.150219,44342,44407,65.0,3,448.0
5597,10,104,4,0,11,25,26,36.801774,10.150219,36.803902,10.145292,44407,44469,62.0,3,499.0
5637,10,104,4,0,12,26,27,36.803902,10.145292,36.806888,10.138377,44469,44569,100.0,3,700.0
5677,10,104,4,0,13,27,28,36.806888,10.138377,36.809601,10.131336,44569,44710,141.0,3,696.0
5718,10,104,4,0,14,28,29,36.809601,10.131336,36.810485,10.126229,44710,44746,36.0,3,466.0
5761,10,104,4,0,15,29,30,36.810485,10.126229,36.812087,10.117408,44746,44839,93.0,3,806.0
5833,10,104,4,0,16,30,31,36.812087,10.117408,36.813025,10.113343,44839,44866,27.0,3,377.0
5911,10,104,4,0,17,31,32,36.813025,10.113343,36.815622,10.099338,44866,44987,121.0,3,1281.0
5949,10,104,4,0,18,32,33,36.815622,10.099338,36.816188,10.096113,44987,45013,26.0,3,294.0
5978,10,104,4,0,19,33,34,36.816188,10.096113,36.812810,10.089279,45013,45138,125.0,3,716.0
6018,10,104,4,0,20,34,35,36.812810,10.089279,36.811423,10.088544,45138,45180,42.0,3,168.0
6049,10,104,4,0,21,35,36,36.811423,10.088544,36.809593,10.091012,45180,45213,33.0,3,300.0
6078,10,104,4,0,22,36,37,36.809593,10.091012,36.807927,10.089301,45213,45263,50.0,3,240.0
6109,10,104,4,0,23,37,38,36.807927,10.089301,36.806810,10.087048,45263,45293,30.0,3,236.0
6129,10,104,4,0,24,38,39,36.806810,10.087048,36.807217,10.082834,45293,45372,79.0,3,378.0
6149,10,104,4,0,25,39,40,36.807217,10.082834,36.809297,10.073925,45372,45435,63.0,3,827.0
6178,10,104,4,0,26,40,41,36.809297,10.073925,36.810962,10.065738,45435,45477,42.0,3,753.0
6209,10,104,4,0,27,41,42,36.810962,10.065738,36.814007,10.059630,45477,45530,53.0,3,641.0